[package]
name = "chur-example"
version.workspace = true
description.workspace = true
edition.workspace = true
publish = false

[dependencies]
tonic.workspace = true
prost.workspace = true
prost-types.workspace = true

[build-dependencies]
chur = { path = "../crates/chur" }