[package]
    name = "chur-macros"

    authors.workspace     = true
    description.workspace = true
    edition.workspace     = true
    license.workspace     = true
    publish.workspace     = true
    readme.workspace      = true
    repository.workspace  = true
    version.workspace     = true

[lib]
    proc-macro = true

[dependencies]
    proc-macro2 = "^1.0"
    syn = "^2.0"
    quote = "^1.0"